version: "3.4"
services:
  exporter:
    build:
      context: .
    restart: always
    runtime: runsc
    # TODO: packaging athens-export in a jar should allow removing this and
    # blocking exporter from having internet access.
    network_mode: bridge
    volumes:
      - ./:/app/src:ro
      - output:/app/output
      - athens_athens_datascript:/app/input:ro
    command:
      python3 exporter.py --input_dir /app/input/persist --config_file /app/src/config.toml
      --athens_export /app/athens-export --obsidian_zola /app/obsidian-zola
      --temp_dir /tmp/exporter --out_dir /app/output
      --debug

  nginx:
    restart: always
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - output:/app/output
    ports:
      - 5102:80

volumes:
  output:
  athens_athens_datascript:
    external: true
